# Generated by Django 4.1.7 on 2023-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0003_rename_zipcode_customer_ac_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ac_number',
            field=models.IntegerField(unique=True),
        ),
    ]
