# Generated by Django 4.1.7 on 2023-10-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0015_transaction_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reciver',
            new_name='receiver',
        ),
    ]
