# Generated by Django 4.1.7 on 2023-10-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0016_rename_reciver_transaction_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.CharField(max_length=30),
        ),
    ]
