# Generated by Django 4.1.7 on 2023-10-27 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donation_Portal', '0017_alter_transaction_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=30)),
                ('sender_paypal_email', models.EmailField(max_length=254)),
                ('receiver_paypal_email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=30)),
                ('mode_of_payment', models.CharField(max_length=20)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
