# Generated by Django 4.1.7 on 2023-10-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0023_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='null', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
