# Generated by Django 4.1.7 on 2023-10-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0024_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
