# Generated by Django 4.1.7 on 2023-10-31 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0029_alter_country_country_name_alter_customuser_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='user_type_2', to='Donation_Portal.usertype', to_field='user_type'),
            preserve_default=False,
        ),
    ]
