# Generated by Django 4.1.7 on 2023-10-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0032_customuser_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Miner',
        ),
    ]
