# Generated by Django 4.1.7 on 2023-11-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0034_alter_customer_country_alter_ngo_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
