# Generated by Django 4.1.7 on 2023-11-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0035_alter_ngo_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_country', to='Donation_Portal.country', to_field='country_name'),
        ),
    ]
