# Generated by Django 4.1.7 on 2023-11-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0036_alter_ngo_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ac_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ifsc_code',
        ),
    ]
