# Generated by Django 4.1.7 on 2023-11-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0037_remove_customer_ac_number_remove_customer_ifsc_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='bank_account_number',
        ),
    ]
