# Generated by Django 4.1.7 on 2023-11-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0038_remove_ngo_bank_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_account',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
