# Generated by Django 4.1.7 on 2023-11-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0041_alter_pool_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='sender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(max_length=30),
        ),
    ]
