# Generated by Django 4.1.7 on 2023-11-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0042_alter_pool_sender_alter_transaction_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='social_media_links',
        ),
    ]
