# Generated by Django 4.1.7 on 2023-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donation_Portal', '0043_remove_ngo_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='contact_person',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
